spring.application.name=loan-system

jdbc.url=jdbc:postgresql://localhost:5432/loan-system?characterEncoding=utf8
jdbc.username=postgres
jdbc.password=1234

database.driverClassName=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update


